@startuml
hide circles
hide empty members
skinparam pathHoverColor red ' on cover, highlight blue links as red
' skinparam topurl https://raw.githack.com/w3c/data-shapes/master/shacl12-core/index.html ' links resolve to anchors in current HTML page, when the SVG is embedded

class "<color:blue><u>sh:Shape" as Shape [[#shapes]] {
  [[#targetClass sh:targetClass]] : rdfs:Class
  [[#targetNode sh:targetNode]] : any
  [[#targetSubjectsOf sh:targetSubjectsOf]] : rdf:Property
  [[#targetObjectsOf sh:targetObjectsOf]] : rdf:Property
  ....
  [[#deactivated sh:deactivated]] : xsd:boolean
  [[#message sh:message]] : xsd:string or rdf:langString
  [[#severity sh:severity]] : sh:Severity
}

class "<color:blue><u>sh:NodeShape" as NodeShape [[#node-shapes]] {
  [[#constraints Constraint parameters]], for example:
  [[#NodeKindConstraintComponent sh:nodeKind]] a sh:NodeKind
  [[#ClosedConstraintComponent sh:closed]] : xsd:boolean or [[#syntax-rule-closed-datatype sh:ByTypes]]
  [[#ClosedConstraintComponent sh:ignoredProperties]] : list
  [[#OrConstraintComponent sh:or]], [[#AndConstraintComponent sh:and]], [[#XoneConstraintComponent sh:xone]] : list of Shape
  [[#NotConstraintComponent sh:not]] : [[#shapes sh:Shape]]
  ...
}

class "<color:blue><u>sh:PropertyShape" as PropertyShape [[#property-shapes]] {
  [[#constraints Constraint parameters]], for example:
  [[#MinCountConstraintComponent sh:minCount]], [[#MaxCountConstraintComponent sh:maxCount]] : xsd:integer
  [[#MinLengthConstraintComponent sh:minLength]], [[#MaxLengthConstraintComponent sh:maxLength]] : xsd:integer
  [[#ClassConstraintComponent sh:class]] or [[#DatatypeConstraintComponent sh:datatype]] : IRI or list of IRIs
  [[#NodeConstraintComponent sh:node]] : [[#node-shapes sh:NodeShape]]
  ...
  ....
  [[#name sh:name]] : xsd:string or rdf:langString
  [[#description sh:description]] : xsd:string or rdf:langString
  [[#syntax-rule-path-defaultValue sh:defaultValue]] : any
  [[#syntax-rule-path-defaultValue sh:values]] : any
  [[#codeIdentifier sh:codeIdentifier]] : xsd:string 
  [[#order sh:order]] : xsd:integer or xsd:decimal
  [[#property-paths sh:path]] : predicate or list or blank node
}

class "<color:blue><u>sh:PropertyGroup" as PropertyGroup [[#group sh:group]] {
  [[#group sh:order]] : xsd:integer or xsd:decimal
  ... eg rdfs:label
}

Shape <|-- NodeShape
Shape <|-- PropertyShape
NodeShape -> PropertyShape : [[#property-shapes sh:property]] *
PropertyShape --> PropertyGroup :  [[#group sh:group]]
@enduml
