@startuml
hide circles
hide empty members
skinparam topurl https://raw.githack.com/w3c/data-shapes/master/shacl12-core/index.html

class "<color:blue><u>sh:Shape" as Shape [[#shapes]] {
  [[#targetClass sh:targetClass]] : rdfs:Class
  [[#targetNode sh:targetNode]] : any
  [[#targetObjectsOf sh:targetObjectsOf]] : rdf:Property
  [[#targetSubjectsOf sh:targetSubjectsOf]] : rdf:Property
  ....
  [[#deactivated sh:deactivated]] : xsd:boolean
  [[#message sh:message]] : xsd:string or rdf:langString
  [[#severity sh:severity]] : sh:Severity
}

class "<color:blue><u>sh:NodeShape" as NodeShape [[#node-shapes]] {
  [[#constraints Constraint parameters]], for example:
  [[#ClosedConstraintComponent sh:closed]] : xsd:boolean or [[#syntax-rule-closed-datatype sh:ByTypes]]
  [[#OrConstraintComponent sh:or]], [[#AndConstraintComponent sh:and]], [[#XoneConstraintComponent sh:xone]] : rdf:List
  [[#NotConstraintComponent sh:not]] : [[#shapes sh:Shape]]
}

class "<color:blue><u>sh:PropertyShape" as PropertyShape [[#property-shapes]] {
  [[#constraints Constraint parameters]], for example:
  [[#MinCountConstraintComponent sh:minCount]], [[#MaxCountConstraintComponent sh:maxCount]] : xsd:integer
  [[#MinLengthConstraintComponent sh:minLength]], [[#MaxLengthConstraintComponent sh:maxLength]] : xsd:integer
  [[#ClassConstraintComponent sh:class]] or [[#DatatypeConstraintComponent sh:datatype]] : rdfs:Resource or\n      rdf:List of rdfs:Resources
  [[#NodeConstraintComponent sh:node]] : [[#node-shapes sh:NodeShape]]
  ....
  [[#name sh:name]] : xsd:string or rdf:langString
  [[#desription sh:description]] : xsd:string or rdf:langString
  [[#syntax-rule-path-defaultValue sh:defaultValue]] : any
  [[#syntax-rule-path-defaultValue sh:values]] : any
  [[#order sh:order]] : number
  [[#property-shapes sh:path]] : rdfs:Resource
}

class "sh:PropertyGroup" as PropertyGroup [[#group sh:group]] {
  [[#group sh:order]] : number
}

Shape <|-- NodeShape
Shape <|-- PropertyShape
NodeShape -> PropertyShape : [[#property-shapes sh:property]] *
PropertyShape --> PropertyGroup :  [[#group sh:group]]
@enduml
