@startuml
hide circles
hide empty members
skinparam pathHoverColor red ' on cover, highlight blue links as red

class "<color:blue><u>sh:ValidationReport" as ValidationReport [[#results-validation-report]] {
  [[#conforms sh:conforms]] : xsd:boolean
  [[#shapesGraphWellFormed sh:shapesGraphWellFormed]] : xsd:boolean
}

class "<color:blue><u>sh:AbstractResult" as AbstractResult <<abstract>> [[#results-validation-result]] {
}

class "<color:blue><u>sh:ValidationResult" as ValidationResult [[#results-validation-result]] {
  [[#results-focus-node sh:focusNode]] : any
  [[#results-path sh:resultPath]] : [[#property-paths SHACL prop path]]
  [[#results-value sh:value]] : any
  [[#results-source-shape sh:sourceShape]] : [[#shapes sh:Shape]]
  [[#results-source-constraint-component sh:sourceConstraintComponent]] : [[#dfn-constraint-component sh:ConstraintComponent]]
  [[#results-message sh:resultMessage]] : xsd:string or rdf:langString
  [[#results-severity sh:resultSeverity]] : [[#severity sh:Severity]]
}

ValidationReport --> ValidationResult : [[#result sh:result]] * 
AbstractResult <|-down- ValidationResult
ValidationResult -up-> AbstractResult : [[#results-detail sh:detail]] * 
@enduml
