[1]    RuleSet                   ::= RuleOrDataBlock
[2]    RuleOrDataBlock           ::= Prologue ( RuleOrData+ ( Prologue1 RuleOrData? )* )?
[3]    RuleOrData                ::= Rule | Data
[4]    Prologue                  ::= Prologue1*
[5]    Prologue1                 ::= BaseDecl | PrefixDecl | VersionDecl | ImportsDecl
[6]    BaseDecl                  ::= 'BASE' IRIREF
[7]    PrefixDecl                ::= 'PREFIX' PNAME_NS IRIREF
[8]    VersionDecl               ::= 'VERSION' VersionSpecifier
[9]    VersionSpecifier          ::= STRING_LITERAL1 | STRING_LITERAL2
[10]   ImportsDecl               ::= 'IMPORTS' iri
[11]   Rule                      ::= Rule1 | Rule2
[12]   Rule1                     ::= 'RULE' iri? HeadTemplate 'WHERE' 'DATA'? BodyPattern
[13]   Rule2                     ::= 'IF' BodyPattern 'THEN' HeadTemplate
[14]   Data                      ::= 'DATA' '{' DataTriplesBlock? '}'
[15]   HeadTemplate              ::= '{' HeadTemplateBlock? '}'
[16]   BodyPattern               ::= '{' BodyTriplesBlock? ( BodyNotTriples '.'? BodyTriplesBlock? )* '}'
[17]   BodyNotTriples            ::= Filter | Negation | Assignment
[18]   Filter                    ::= 'FILTER' Constraint
[19]   Constraint                ::= BrackettedExpression | BuiltInCall | FunctionCall
[20]   FunctionCall              ::= iri ArgList
[21]   ArgList                   ::= NIL | '(' Expression ( ',' Expression )* ')' 
[22]   ExpressionList            ::= NIL | '(' Expression ( ',' Expression )* ')' 
[23]   Negation                  ::= 'NOT' 'DATA'? '{' BodyBasic '}'
[24]   BodyBasic                 ::= BodyTriplesBlock? ( BodyBasicNotTriples '.'? BodyTriplesBlock? )*
[25]   BodyBasicNotTriples       ::= Filter
[26]   Assignment                ::= 'SET' '(' Var ':=' Expression ')'
[27]   DataTriplesBlock          ::= TriplesSameSubjectData ( '.' DataTriplesBlock? )?
[28]   TriplesSameSubjectData    ::= RDFTermData PropertyListNotEmptyData | TriplesNodeData PropertyListData | ReifiedTripleBlockData
[29]   PropertyListData          ::= PropertyListNotEmptyData?
[30]   PropertyListNotEmptyData  ::= VerbData ObjectListData ( ';' ( VerbData ObjectListData )? )*
[31]   VerbData                  ::= iri | 'a'
[32]   ObjectListData            ::= ObjectData ( ',' ObjectData )*
[33]   ObjectData                ::= GraphNodeData AnnotationData
[34]   GraphNodeData             ::= RDFTermData | TriplesNodeData | ReifiedTripleData
[35]   TriplesNodeData           ::= CollectionData | BlankNodePropertyListData
[36]   BlankNodePropertyListData ::= '[' PropertyListNotEmptyData ']'
[37]   CollectionData            ::= '(' GraphNodeData+ ')'
[38]   AnnotationData            ::= ( ReifierData | AnnotationBlockData )*
[39]   AnnotationBlockData       ::= '{|' PropertyListNotEmptyData '|}'
[40]   ReifierData               ::= '~' ReifierIdData?
[41]   ReifierIdData             ::= iri | BlankNode
[42]   ReifiedTripleBlockData    ::= ReifiedTripleData PropertyListData
[43]   ReifiedTripleData         ::= '<<' ReifiedTripleSubjectData VerbData ReifiedTripleObjectData ReifierData? '>>'
[44]   ReifiedTripleSubjectData  ::= iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | ReifiedTripleData | TripleTermData
[45]   ReifiedTripleObjectData   ::= iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | ReifiedTripleData | TripleTermData
[46]   TripleTermData            ::= '<<(' TripleTermSubjectData VerbData TripleTermObjectData ')>>'
[47]   TripleTermSubjectData     ::= iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | TripleTermData
[48]   TripleTermObjectData      ::= iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | TripleTermData
[49]   HeadTemplateBlock         ::= TriplesBlockTemplate
[50]   TriplesBlockTemplate      ::= TriplesSameSubjectTemplate ( '.' TriplesBlockTemplate? )?
[51]   TriplesSameSubjectTemplate ::= VarOrRDFTerm PropertyListNotEmptyTemplate | TriplesNodeTemplate PropertyListTemplate | ReifiedTripleBlockTemplate
[52]   PropertyListTemplate      ::= PropertyListNotEmptyTemplate?
[53]   PropertyListNotEmptyTemplate ::= Verb ObjectListTemplate ( ';' ( Verb ObjectListTemplate )? )*
[54]   ObjectListTemplate        ::= ObjectTemplate ( ',' ObjectTemplate )*
[55]   ObjectTemplate            ::= GraphNodeTemplate AnnotationTemplate
[56]   GraphNodeTemplate         ::= VarOrRDFTerm | TriplesNodeTemplate | ReifiedTriple
[57]   TriplesNodeTemplate       ::= CollectionTemplate | BlankNodePropertyListTemplate
[58]   BlankNodePropertyListTemplate ::= '[' PropertyListNotEmptyTemplate ']'
[59]   CollectionTemplate        ::= '(' GraphNodeTemplate+ ')'
[60]   AnnotationTemplate        ::= ( Reifier | AnnotationBlockTemplate )*
[61]   AnnotationBlockTemplate   ::= '{|' PropertyListNotEmptyTemplate '|}'
[62]   ReifiedTripleBlockTemplate ::= ReifiedTriple PropertyListTemplate
[63]   BodyTriplesBlock          ::= TriplesBlockPattern
[64]   TriplesBlockPattern       ::= TriplesSameSubjectPattern ( '.' TriplesBlockPattern? )?
[65]   ReifiedTripleBlockPattern ::= ReifiedTriple PropertyListPattern
[66]   TriplesSameSubjectPattern ::= VarOrRDFTerm PropertyListNotEmptyPattern | TriplesNodePattern PropertyListPattern | ReifiedTripleBlockPattern
[67]   PropertyListPattern       ::= PropertyListNotEmptyPattern?
[68]   PropertyListNotEmptyPattern ::= ( VerbPath | Var ) ObjectListPattern ( ';' ( ( VerbPath | Var ) ObjectListPattern )? )*
[69]   ObjectListPattern         ::= ObjectPattern ( ',' ObjectPattern )*
[70]   ObjectPattern             ::= GraphNodePattern AnnotationPattern
[71]   TriplesNodePattern        ::= CollectionPattern | BlankNodePropertyListPattern
[72]   BlankNodePropertyListPattern ::= '[' PropertyListNotEmptyPattern ']'
[73]   CollectionPattern         ::= '(' GraphNodePattern+ ')'
[74]   AnnotationPattern         ::= ( Reifier | AnnotationBlockPattern )*
[75]   AnnotationBlockPattern    ::= '{|' PropertyListNotEmptyPattern '|}'
[76]   GraphNodePattern          ::= VarOrRDFTerm | TriplesNodePattern | ReifiedTriple
[77]   Reifier                   ::= '~' ReifierId?
[78]   ReifierId                 ::= Var | iri | BlankNode
[79]   ReifiedTriple             ::= '<<' ReifiedTripleSubject Verb ReifiedTripleObject Reifier? '>>'
[80]   ReifiedTripleSubject      ::= Var | iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | ReifiedTriple | TripleTerm
[81]   ReifiedTripleObject       ::= Var | iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | ReifiedTriple | TripleTerm
[82]   TripleTerm                ::= '<<(' TripleTermSubject Verb TripleTermObject ')>>'
[83]   TripleTermSubject         ::= Var | iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | TripleTerm
[84]   TripleTermObject          ::= Var | iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | TripleTerm
[85]   Verb                      ::= VarOrIri | 'a'
[86]   VerbPath                  ::= Path
[87]   Path                      ::= PathSequence
[88]   PathSequence              ::= PathEltOrInverse ( '/' PathEltOrInverse )*
[89]   PathEltOrInverse          ::= PathElt | '^' PathElt
[90]   PathElt                   ::= ( iri | 'a' | '(' Path ')' )
[91]   RDFTermData               ::= iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | NIL | TripleTermData
[92]   VarOrRDFTerm              ::= Var | iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | NIL | TripleTerm
[93]   VarOrIri                  ::= Var | iri
[94]   Var                       ::= VAR1 | VAR2
[95]   RDFLiteral                ::= String ( LANG_DIR | '^^' iri )?
[96]   NumericLiteral            ::= NumericLiteralUnsigned | NumericLiteralPositive | NumericLiteralNegative
[97]   NumericLiteralUnsigned    ::= INTEGER | DECIMAL | DOUBLE
[98]   NumericLiteralPositive    ::= INTEGER_POSITIVE | DECIMAL_POSITIVE | DOUBLE_POSITIVE
[99]   NumericLiteralNegative    ::= INTEGER_NEGATIVE | DECIMAL_NEGATIVE | DOUBLE_NEGATIVE
[100]  BooleanLiteral            ::= 'true' | 'false'
[101]  String                    ::= STRING_LITERAL1 | STRING_LITERAL2 | STRING_LITERAL_LONG1 | STRING_LITERAL_LONG2
[102]  iri                       ::= IRIREF | PrefixedName
[103]  PrefixedName              ::= PNAME_LN | PNAME_NS
[104]  BlankNode                 ::= BLANK_NODE_LABEL | ANON
[105]  Expression                ::= ConditionalOrExpression
[106]  ConditionalOrExpression   ::= ConditionalAndExpression ( '||' ConditionalAndExpression )*
[107]  ConditionalAndExpression  ::= ValueLogical ( '&&' ValueLogical )*
[108]  ValueLogical              ::= RelationalExpression
[109]  RelationalExpression      ::= NumericExpression ( '=' NumericExpression | '!=' NumericExpression | '<' NumericExpression | '>' NumericExpression | '<=' NumericExpression | '>=' NumericExpression | 'IN' ExpressionList | 'NOT' 'IN' ExpressionList )?
[110]  NumericExpression         ::= AdditiveExpression
[111]  AdditiveExpression        ::= MultiplicativeExpression ( '+' MultiplicativeExpression | '-' MultiplicativeExpression | ( NumericLiteralPositive | NumericLiteralNegative ) ( ( '*' UnaryExpression ) | ( '/' UnaryExpression ) )* )*
[112]  MultiplicativeExpression  ::= UnaryExpression ( '*' UnaryExpression | '/' UnaryExpression )*
[113]  UnaryExpression           ::= '!' PrimaryExpression 
                                   | '+' PrimaryExpression 
                                   | '-' PrimaryExpression 
                                   | PrimaryExpression
[114]  PrimaryExpression         ::= BrackettedExpression | BuiltInCall | iriOrFunction | RDFLiteral | NumericLiteral | BooleanLiteral | Var | ExprTripleTerm
[115]  iriOrFunction             ::= iri ArgList?
[116]  ExprTripleTerm            ::= '<<(' ExprTripleTermSubject Verb ExprTripleTermObject ')>>'
[117]  ExprTripleTermSubject     ::= iri | RDFLiteral | NumericLiteral | BooleanLiteral | Var
[118]  ExprTripleTermObject      ::= iri | RDFLiteral | NumericLiteral | BooleanLiteral | Var | ExprTripleTerm
[119]  BrackettedExpression      ::= '(' Expression ')'
[120]  BuiltInCall               ::= 'STR' '(' Expression ')' 
                                   | 'LANG' '(' Expression ')' 
                                   | 'LANGMATCHES' '(' Expression ',' Expression ')' 
                                   | 'LANGDIR' '(' Expression ')' 
                                   | 'DATATYPE' '(' Expression ')' 
                                   | 'IRI' '(' Expression ')' 
                                   | 'URI' '(' Expression ')' 
                                   | 'BNODE' ( '(' Expression ')' | NIL ) 
                                   | 'ABS' '(' Expression ')' 
                                   | 'CEIL' '(' Expression ')' 
                                   | 'FLOOR' '(' Expression ')' 
                                   | 'ROUND' '(' Expression ')' 
                                   | 'CONCAT' ExpressionList 
                                   | 'SUBSTR' '(' Expression ',' Expression ( ',' Expression )? ')' 
                                   | 'STRLEN' '(' Expression ')' 
                                   | 'REPLACE' '(' Expression ',' Expression ',' Expression ( ',' Expression )? ')' 
                                   | 'UCASE' '(' Expression ')' 
                                   | 'LCASE' '(' Expression ')' 
                                   | 'ENCODE_FOR_URI' '(' Expression ')' 
                                   | 'CONTAINS' '(' Expression ',' Expression ')' 
                                   | 'STRSTARTS' '(' Expression ',' Expression ')' 
                                   | 'STRENDS' '(' Expression ',' Expression ')' 
                                   | 'STRBEFORE' '(' Expression ',' Expression ')' 
                                   | 'STRAFTER' '(' Expression ',' Expression ')' 
                                   | 'YEAR' '(' Expression ')' 
                                   | 'MONTH' '(' Expression ')' 
                                   | 'DAY' '(' Expression ')' 
                                   | 'HOURS' '(' Expression ')' 
                                   | 'MINUTES' '(' Expression ')' 
                                   | 'SECONDS' '(' Expression ')' 
                                   | 'TIMEZONE' '(' Expression ')' 
                                   | 'TZ' '(' Expression ')' 
                                   | 'NOW' NIL 
                                   | 'UUID' NIL 
                                   | 'STRUUID' NIL 
                                   | 'IF' '(' Expression ',' Expression ',' Expression ')' 
                                   | 'STRLANG' '(' Expression ',' Expression ')' 
                                   | 'STRLANGDIR' '(' Expression ',' Expression ',' Expression ')' 
                                   | 'STRDT' '(' Expression ',' Expression ')' 
                                   | 'sameTerm' '(' Expression ',' Expression ')' 
                                   | 'isIRI' '(' Expression ')' 
                                   | 'isURI' '(' Expression ')' 
                                   | 'isBLANK' '(' Expression ')' 
                                   | 'isLITERAL' '(' Expression ')' 
                                   | 'isNUMERIC' '(' Expression ')' 
                                   | 'hasLANG' '(' Expression ')' 
                                   | 'hasLANGDIR' '(' Expression ')' 
                                   | 'REGEX' '(' Expression ',' Expression ( ',' Expression )? ')' 
                                   | 'isTRIPLE' '(' Expression ')' 
                                   | 'TRIPLE' '(' Expression ',' Expression ',' Expression ')' 
                                   | 'SUBJECT' '(' Expression ')' 
                                   | 'PREDICATE' '(' Expression ')' 
                                   | 'OBJECT' '(' Expression ')'

@terminals

[121]  IRIREF                    ::= '<' ([^<>"{}|^`\]-[#x00-#x20] | <UCHAR> )* '>'
[122]  PNAME_NS                  ::= PN_PREFIX? ':'
[123]  PNAME_LN                  ::= PNAME_NS PN_LOCAL
[124]  BLANK_NODE_LABEL          ::= '_:' ( PN_CHARS_U | [0-9] ) ((PN_CHARS|'.')* PN_CHARS)?
[125]  VAR1                      ::= '?' VARNAME
[126]  VAR2                      ::= '$' VARNAME
[127]  LANG_DIR                  ::= '@' [a-zA-Z]+ ('-' [a-zA-Z0-9]+)* ('--' [a-zA-Z]+)?
[128]  INTEGER                   ::= [0-9]+
[129]  DECIMAL                   ::= [0-9]* '.' [0-9]+
[130]  DOUBLE                    ::= ( ([0-9]+ ('.'[0-9]*)? ) | ( '.' ([0-9])+ ) ) [eE][+-]?[0-9]+
[131]  INTEGER_POSITIVE          ::= '+' INTEGER
[132]  DECIMAL_POSITIVE          ::= '+' DECIMAL
[133]  DOUBLE_POSITIVE           ::= '+' DOUBLE
[134]  INTEGER_NEGATIVE          ::= '-' INTEGER
[135]  DECIMAL_NEGATIVE          ::= '-' DECIMAL
[136]  DOUBLE_NEGATIVE           ::= '-' DOUBLE
[137]  STRING_LITERAL1           ::= "'" ( ([^#x27#x5C#xA#xD]) | ECHAR | UCHAR )* "'"
[138]  STRING_LITERAL2           ::= '"' ( ([^#x22#x5C#xA#xD]) | ECHAR | UCHAR )* '"'
[139]  STRING_LITERAL_LONG1      ::= "'''" ( ( "'" | "''" )? ( [^'\] | ECHAR | UCHAR ) )* "'''"
[140]  STRING_LITERAL_LONG2      ::= '"""' ( ( '"' | '""' )? ( [^"\] | ECHAR | UCHAR ) )* '"""'
[141]  ECHAR                     ::= '\' [tbnrf\"']
[142]  UCHAR                     ::= ('\u' HEX HEX HEX HEX) | ('\U' HEX HEX HEX HEX HEX HEX HEX HEX)
[143]  NIL                       ::= '(' WS* ')'
[144]  WS                        ::= #x20 | #x9 | #xD | #xA
[145]  ANON                      ::= '['  WS* ']'
[146]  PN_CHARS_BASE             ::= [A-Z] 
                                   | [a-z] 
                                   | [#x00C0-#x00D6] 
                                   | [#x00D8-#x00F6] 
                                   | [#x00F8-#x02FF] 
                                   | [#x0370-#x037D] 
                                   | [#x037F-#x1FFF] 
                                   | [#x200C-#x200D] 
                                   | [#x2070-#x218F] 
                                   | [#x2C00-#x2FEF] 
                                   | [#x3001-#xD7FF] 
                                   | [#xF900-#xFDCF] 
                                   | [#xFDF0-#xFFFD] 
                                   | [#x10000-#xEFFFF]
[147]  PN_CHARS_U                ::= PN_CHARS_BASE | '_'
[148]  VARNAME                   ::= ( PN_CHARS_U  | [0-9] ) ( PN_CHARS_U | [0-9] | #x00B7 | [#x0300-#x036F] | [#x203F-#x2040] )*
[149]  PN_CHARS                  ::= PN_CHARS_U | '-' | [0-9] | #x00B7 | [#x0300-#x036F] | [#x203F-#x2040]
[150]  PN_PREFIX                 ::= PN_CHARS_BASE ((PN_CHARS|'.')* PN_CHARS)?
[151]  PN_LOCAL                  ::= (PN_CHARS_U | ':' | [0-9] | PLX ) ((PN_CHARS | '.' | ':' | PLX)* (PN_CHARS | ':' | PLX) )?
[152]  PLX                       ::= PERCENT | PN_LOCAL_ESC
[153]  PERCENT                   ::= '%' HEX HEX
[154]  HEX                       ::= [0-9] | [A-F] | [a-f]
[155]  PN_LOCAL_ESC              ::= '\' ( '_' | '~' | '.' | '-' | '!' | '$' | '&' | "'" | '(' | ')' | '*' | '+' | ',' | ';' | '=' | '/' | '?' | '#' | '@' | '%' )
