# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  REPO_ROOT:
    sh: git rev-parse --show-toplevel
  WORKFLOW_FILE: "{{.REPO_ROOT}}/.github/workflows/shacl-ui-validation.yml"

tasks:
  validate:
    desc: Run SHACL UI Validation Workflow
    dir: "{{.REPO_ROOT}}"
    cmd: act pull_request -W "{{.WORKFLOW_FILE}}" -j validate-widget-scores --container-architecture linux/amd64
